# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aab427add1389bf4987a57e3b884490577122185aacf8d801a67e598dbe030c4593b01fae39a7afe63bad3f22516f204fedacca464bc417590f948e2449b0d64

test:
  secret_key_base: 0c2b61950df01377b627709d765c03b515432b12c02f998d75797c3dd60fe0333c321189274c3147ec5dc84c2ba86d86f3221f1c6699290a0e041bb45b30c98a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
